<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="AI1temp" Id="{e24d3ffd-744f-4359-86df-6eb2938322be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AI1temp : INT
VAR_INPUT
	AI1raw : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Description: 
Function performs the 0-32767 offset+scaling+interpretation to a Cel temp for AI0. Matched to PWM Reciever board CH1
EL3XXX converts the interpreted 0-32767 value into voltage.
Voltage is converted to temperature using a calibrated formula: (scale*volt)-offset=temp

For IR sensor Ch1*)
AI1temp := REAL_TO_INT( ((1.842963*(INT_TO_REAL(AI1raw)*0.0003049947521145891)+4)-4.0 ) *450.0/16.0 - 70.0 ) ;
// Calibrated Dec 9, 2021.]]></ST>
    </Implementation>
    <LineIds Name="AI1temp">
      <LineId Id="33" Count="6" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>