<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="AI3temp" Id="{7683f37e-a0a3-41b5-a199-d1ce05f8bc28}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AI3temp : INT
VAR_INPUT
	AI3raw : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Description: 
Function performs the 0-32767 offset+scaling+interpretation to a Cel temp for AI0. Matched to PWM Reciever board CH3
EL3XXX converts the interpreted 0-32767 value into voltage.
Voltage is converted to temperature using a calibrated formula: (scale*volt)-offset=temp

For IR sensor Ch3*)
AI3temp := REAL_TO_INT( ((1.842963*(INT_TO_REAL(AI3raw)*0.0003049947521145891)+4)-4.0 ) *450.0/16.0 - 70.0 ) ;
//AI3temp := REAL_TO_INT( (( INT_TO_REAL(AI3raw)*0.0005058939598786860088 + 3.3586439434355245368)-4.0 ) *450.0/16.0 - 31.0) ;
// Calibrated Dec 9, 2021.]]></ST>
    </Implementation>
    <LineIds Name="AI3temp">
      <LineId Id="27" Count="5" />
      <LineId Id="40" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>