<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{d4510c44-5a58-4477-924a-86d697b0947a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Alias();
Heartbeat();
Permissives();
Trips();
Alarms();
Sequence();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="3" />
      <LineId Id="13" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>