<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{975ec784-f55e-4f2c-81eb-efc062cbd761}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Alias();
Permissives();
Trips();
ChargeTime();
AnalogConversion();
VoltMonitor();
Sequence();
HMI();
Heartbeat();
Alarms();
RW_CSV();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="67" Count="8" />
      <LineId Id="54" Count="0" />
      <LineId Id="80" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>