<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{975ec784-f55e-4f2c-81eb-efc062cbd761}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Alias();
Permissives();
Trips();
ChargeTime();
AnalogConversion();
VoltMonitor();
Sequence();
HMI();
Heartbeat();
Alarms();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="43" Count="1" />
      <LineId Id="53" Count="0" />
      <LineId Id="45" Count="4" />
      <LineId Id="17" Count="0" />
      <LineId Id="54" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>