<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="VoltageMon" Id="{b1c07060-731f-40a5-b605-19acb84a399f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM VoltageMon
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="VoltageMon">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>