<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{c44dd456-9fdd-4969-ac7e-7e1422e6d84f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ALIAS();
ANALOGconversion();
handleFAULT();
handlesensorlimitFAULTS();
handlesoftEXCEPTION();
Automated_Capacitor_Test_ST();	
HMI();
HV_Monitor();
VoltMonitor();
// runningLIGHTS();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="5" />
      <LineId Id="13" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>